- name: install sources.list. may use apt-cacher if ubuntu_apt_server var is set
  template: src=apt_sources.list.j2  dest=/etc/apt/sources.list

- name: run apt-get update
  apt: update_cache=yes

- name: install service packages
  apt: name={{item}} state=present
  with_items:
    - isc-dhcp-server
    - bind9
    - software-properties-common
    - git

- name: add ansible repo
  apt_repository: repo={{item}}
  with_items:
    - ppa:ansible/ansible

- name: update apt cache
  apt: update_cache=yes

- name: Install Ansible
  apt: pkg=ansible state=present

- name: Git clone cldemo-indie
  git: repo=https://github.com/sciarrilli/cldemo-indie.git dest=/home/cumulus/cldemo-indie

- name: configure dhcpd.conf
  template: src=dhcpd.conf.j2 dest=/etc/dhcp/dhcpd.conf
  notify: restart dhcp

- name: configure dhcpd.pool
  template: src=dhcpd.pools.j2 dest=/etc/dhcp/dhcpd.pools
  notify: restart dhcp

- name: configure dhcpd.hosts
  template: src=dhcpd.hosts.j2 dest=/etc/dhcp/dhcpd.hosts
  notify: restart dhcp

- name: update named.conf.locals bind file
  copy: src=named.conf.local dest=/etc/bind/named.conf.local
  notify: restart bind9

- name: create bind9 zone directory
  file: path=/etc/bind/zones state=directory
  notify: restart bind9

- name: install db.lab.local zone
  template: src=db.lab.local.j2 dest=/etc/bind/zones/db.lab.local
  notify: restart bind9

- name: install reverse db.lab.local zone file
  template: src=db.0.168.192.in-addr.arpa.j2 dest=/etc/bind/zones/db.0.168.192.in-addr.arpa
  notify: restart bind9

- name: set up bind forwarding
  template: src=named.conf.options.j2 dest=/etc/bind/named.conf.options
  notify: restart bind9

- name: make wbench use itself as DNS resolver
  copy: src=resolv.conf dest=/etc/resolv.conf
  notify: restart bind9

- name: really restart bind
  meta: flush_handlers

- name: pause and let bind restart
  pause: seconds=10

- name: copy ztp script
  template: src=ztp.sh.j2 dest=/var/www/ztp.sh

- name: copy ptm toplolgy
  copy: src=topology.dot dest=/var/www/toplolgy.dot

- name: copy license file
  copy: src=license.lic dest=/var/www/license.lic
